Documentation: Azure Functions Deployment
apollographql/apollo-server pull request #5675
Opened 2021-08-31 15:12 UTC by SameerDoshi

Adding additional documentation on accessing request headers when dep…loying Apollo Server in an Azure function.

Big picture: Running Apollo in an Azure Function where Apollo access protected backend APIs a user might want to pass a user provided token to the backend API.

2021-08-31 15:12 UTC, apollo-cla commented
@SameerDoshi: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2021-09-14 20:43 UTC, glasser requested changes
For what it's worth, I'd suggest we focus more on our docs site and less on the individual package READMEs instead of having two separate places to look for information.

https://www.apollographql.com/docs/apollo-server/deployment/azure-functions/ is the docs page, with source at `docs/source/deployment/azure-functions.md`. The [Lambda docs page](https://www.apollographql.com/docs/apollo-server/deployment/lambda/#getting-request-info) has a nice section on this sort of thing that could be copied and adapted into the Azure section.

2021-09-14 20:43 UTC, glasser commented on packages/apollo-server-azure-functions/README.md
> +By default Azure Functions will pass the request object as req.  Pass this into the context of the ApolloServer constructor to access request contents.  For example for passing an auth token to a bac
req is just the name you're choosing for an argument here, FWIW.

2021-09-14 20:43 UTC, glasser commented on packages/apollo-server-azure-functions/README.md
> +          const authHeader = req.context.bindings.req.headers.authorization || '';
Is that actually the best way to get a header? I see at https://www.apollographql.com/docs/apollo-server/api/apollo-server/#middleware-specific-context-fields that we pass `context` and also `request`. Wouldn't `req.request.headers` be simpler?

2021-09-14 20:43 UTC, glasser commented on packages/apollo-server-azure-functions/README.md
> +          if (authHeader === '') throw new AuthenticationError('please send       Bearer token with request');
weird spacing in the error message

2021-09-14 20:43 UTC, glasser commented on packages/apollo-server-azure-functions/README.md
> +* azure-function-log-intercept - console.* messages appear in teh functions log.
Not sure how helpful this is without an example of how to use it. Also typo "teh" vs "the".

2022-10-18 23:42 UTC, trevor-scheer commented
Going to close this since it's no longer mergeable. I've captured it in a [separate issue here](https://github.com/apollographql/apollo-server/issues/7056#issuecomment-1283141566) which is concerned with providing getting started guides for serverless applications.

2022-10-18 23:42 UTC, closed without merging