add types to executeOperation
apollographql/apollo-server pull request #5847
Opened 2021-10-28 22:27 UTC by mmahalwy

With `executeOperation` becoming the way to test queries and mutations, we lost the ability to specify the returned data and variables needed that existed in apollo-server 2. This adds the ability to add this to `executeOperation` and solve this issue https://github.com/apollographql/apollo-server/issues/5464

Looking for feedback here. I felt like there are one of two ways to tackle this:
- Make this work for `executeOperation` only
- Make `GraphQLRequest` and `GraphQLResponse` generic

Thoughts?

2021-11-03 07:55 UTC, mmahalwy commented
@glasser hey - any feedback on this?

2021-11-03 19:27 UTC, glasser commented
Haven't had a chance to review yet!

Are you aware that CI is failing to build it?

2021-11-03 21:20 UTC, mmahalwy commented
@glasser yep - aware of CI failing. It's a type error. Easy fix but wanted to make sure we are aligned on implementation first or you truly want `GraphQLRequest` to be a generic

2021-11-04 00:37 UTC, glasser requested changes
It would help to see an example of how this code ends up being used.

Is implementing this just for executeOperation an incremental step towards generifying everything or is it a different choice that prevents us from doing that later?

2021-11-04 00:37 UTC, glasser commented on packages/apollo-server-core/src/ApolloServer.ts
> +import { buildServiceDefinition } from '@apollographql/apollo-tools';
A lot moved around here — did you run some sort of import-sorting script?

2021-11-04 00:37 UTC, glasser commented on packages/apollo-server-core/src/ApolloServer.ts
> +    } & { variables?: TVariables | VariableValues },
Do we want to add `variables` to the `Omit` above like `query` is?

I don't really understand what the `|` is doing here: why not just TVariables?

2021-11-04 00:37 UTC, glasser commented on packages/apollo-server-core/src/ApolloServer.ts
> +  ): Promise<GraphQLResponse & { data?: TData | null }> {
Do we want to `Omit` data from GraphQLResponse like we do with query above? Or was that actually a pointless thing to do for query too?

2021-11-04 01:04 UTC, mmahalwy commented
@glasser yes. Goal here is being able to type check the variables and output. Usage:

```ts
server.executeOperation<SomeQuery, SomeQueryVariables>()
```

2021-11-04 05:42 UTC, glasser commented
Cool. And is the goal to still get TypedDocumentNode working? Will this change be compatible with that?

2021-11-04 16:22 UTC, mmahalwy commented
@glasser thats a very good question that I unfortunately don't have an answer to nor have context about what `TypedDocumentNode` is. Rather, my goal was to re-add types back to tests since typing was removed when `apollo-testing-server` was deprecated

2021-11-16 01:44 UTC, mmahalwy commented
@glasser bump :)

2021-11-20 00:37 UTC, glasser commented
I don't want to change anything about typing for executeOperation that may make it *harder* to later change it to work with TypedDocumentNode.

TypedDocumentNode is a class that code generators like graphql-code-generator know how to generate which both contains the actual parsed document and proper typings for it. So instead of having to manually make sure that the types you put in `<>` match the operation, you let codegen make it impossible to mess up.  https://github.com/dotansimha/graphql-typed-document-node or https://www.graphql-code-generator.com/docs/plugins/typed-document-node for details.

2022-03-03 18:25 UTC, mmahalwy commented
closing this :(

2022-03-03 18:25 UTC, closed without merging