NEBULA-1385: Add initial state to embeddable sandbox and HTML unit tests
apollographql/apollo-server pull request #6633
Opened 2022-06-29 22:36 UTC by William010x

[Context](https://github.com/apollographql/apollo-server/pull/6628#pullrequestreview-1023862725)

2022-06-29 22:38 UTC, William010x commented
@trevor-scheer I didn't end up porting the changes from `tsconfig.test.json` . Is that fine?

2022-07-05 20:24 UTC, trevor-scheer requested changes

2022-07-05 20:24 UTC, trevor-scheer commented on packages/server/src/plugin/landingPage/default/index.ts
> +export const getEmbeddedSandboxHTML = (
In AS4, our imports are set up a bit differently.

Now, to import this plugin, you would:

`import ... from '@apollo/server/plugin/landingPage/default';`

This means that exports from this `index.ts` file that we're in are part of the public API (they can be imported by users now), and I'd prefer if we don't make that the case. Can we move these to an adjacent file(s)? i.e. `getEmbeddedSandboxHTML.ts` and `getEmbeddedSandboxHTML.ts` so they aren't exported from the `index.ts` _but_ are still accessible internally and for tests?

2022-07-05 20:24 UTC, trevor-scheer commented on packages/server/src/plugin/landingPage/__tests__/getEmbeddedExplorerHTML.test.ts
> +import { getEmbeddedExplorerHTML } from '../default/index';
These test files should be moved to `src/__tests__/plugin/landingPage` (and then there's no need to worry about changes to the tsconfig as you mentioned).

2022-07-08 18:02 UTC, trevor-scheer approved these changes

2022-07-08 18:06 UTC, merged