[docs] Add docs on how to set a REST timeout
apollographql/apollo-server pull request #7373
Opened 2023-02-10 18:41 UTC by smyrick

The docs for `@apollo/datasource-rest` are missing info about how to set a timeout. While this feature is not directly handled by the Apollo package and instead is really information about how to use the `fetch()` API, we can add this common use case here and link off to MDN for more info.

2023-02-10 18:48 UTC, smyrick commented
cc @StephenBarlow for docs review

2023-02-16 21:48 UTC, trevor-scheer requested changes
Suggested some tweaks which you're welcome to take wholesale or make your own adjustments to.

2023-02-16 21:48 UTC, trevor-scheer commented on docs/source/data/fetching-rest.mdx
> +When you make a call to one of the REST methods, the second parameter has some predefined TypeScript types provided by `@apollo/datasource-rest`, but ultimately it is the same `options` object that i
```suggestion
The second parameter to each of the REST methods is the request options object. This object includes some of the common options you might typically pass to [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#syntax), including `method`, `headers`, `body`, and `signal`. If you are looking for other advanced options that you cannot find in the Apollo docs, you can set them here and refer to your Fetch API docs.
```

2023-02-16 21:48 UTC, trevor-scheer commented on docs/source/data/fetching-rest.mdx
> +To set a timeout with a fetch implementation you need to set the `signal` option to an [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) which will allow you to abort the re
```suggestion
To set a `fetch` timeout, you need to provide an [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) via the `signal` option which will allow you to abort the request with custom logic.
```

2023-02-16 21:48 UTC, trevor-scheer commented on docs/source/data/fetching-rest.mdx
> +this.get('/movies/1', {signal: AbortSignal.timeout(myTimeoutMilliseconds)});
```suggestion
this.get('/movies/1', { signal: AbortSignal.timeout(myTimeoutMilliseconds) });
```

2023-02-16 21:59 UTC, trevor-scheer approved these changes

2023-02-16 22:10 UTC, StephenBarlow approved these changes
Approved with small suggestions!

2023-02-16 22:10 UTC, StephenBarlow commented on docs/source/data/fetching-rest.mdx
> +The second parameter to each of the REST methods is the request options object. This object includes some of the common options you might typically pass to [`fetch`](https://developer.mozilla.org/en-
```suggestion
The second parameter passed to each REST method is an object containing request options. These include options commonly passed to [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#syntax), including `method`, `headers`, `body`, and `signal`.

> If you're looking for other advanced options that aren't covered in the Apollo docs, you can set them here and refer to your Fetch API docs.
```

2023-02-16 22:10 UTC, StephenBarlow commented on docs/source/data/fetching-rest.mdx
> +To set a `fetch` timeout, you need to provide an [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) via the `signal` option which will allow you to abort the request with c
```suggestion
To set a `fetch` timeout, provide an [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) via the `signal` option, which enables you to abort the request with custom logic.
```

2023-02-16 22:10 UTC, StephenBarlow commented on docs/source/data/fetching-rest.mdx
> +```
````suggestion
Here's an example of a simple timeout after a fixed time for every request:

```
````

2023-02-17 05:41 UTC, merged