fix: export types form response cache plugin
apollographql/apollo-server pull request #7439
Opened 2023-03-13 13:00 UTC by Igloczek

This small change exposes all types used by the response cache plugin, and alow developers to use
```ts
import type { ApolloServerPluginResponseCacheOptions } from "@apollo/server-plugin-response-cache"
```
instead of
```ts
import type { ApolloServerPluginResponseCacheOptions } from "@apollo/server-plugin-response-cache/dist/esm/ApolloServerPluginResponseCache"
```
which is hard to use with ESM imports.

Additionally, it aligns nicer with the style of other packages in this, since it seems to be a pattern to keep everything in `index.ts`

# Alternative approach
Adjust the import/export in `index.ts`
```ts
export * from './ApolloServerPluginResponseCache.js';
```

2023-03-13 13:00 UTC, apollo-cla commented
@Igloczek: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2023-03-13 17:50 UTC, trevor-scheer requested changes
@Igloczek I'm good with the changes in concept but can you get this into a reviewable / less git-noisy state? I'd prefer if we just export the thing(s) you need from `index.ts` instead of move everything into it.

Can you please add a patch changeset by running `npx changeset`?

2023-03-14 07:31 UTC, Igloczek commented
@trevor-scheer sure thing, all requested changes applied

2023-03-14 22:53 UTC, trevor-scheer approved these changes
Thanks!

2023-03-14 22:54 UTC, merged