Fix for https://github.com/apollographql/apollo-server/issues/7768
apollographql/apollo-server pull request #7769
Opened 2023-10-24 23:30 UTC by cwikla

In packages/server/src/plugin/schemaReporting/schemaReporter.ts

pollTimer is typed as NodeJS.Timer, it is actually a timeout, so using node 18> types it is incompatible
with clearTimeout()

It should be:

private pollTimer?: ReturnType<typeof setTimeout>;

2023-10-24 23:30 UTC, apollo-cla commented
@cwikla: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2023-10-26 14:42 UTC, trevor-scheer requested changes
Thanks for the PR! Can you please add a patch changeset by running `npx changeset`?

2023-10-26 14:42 UTC, trevor-scheer commented on packages/server/src/plugin/schemaReporting/schemaReporter.ts
> +  private pollTimer?: ReturnType<typeof setTimeout>;
```suggestion
  private pollTimer?: NodeJS.Timeout;
```

2023-10-26 21:18 UTC, cwikla commented on packages/server/src/plugin/schemaReporting/schemaReporter.ts
> +  private pollTimer?: ReturnType<typeof setTimeout>;
Changed.

2023-10-26 21:29 UTC, trevor-scheer approved these changes
Perfect, thanks!

2023-10-26 21:31 UTC, merged